<%@ Page Title="" Language="C#" MasterPageFile="~/Main.master" AutoEventWireup="true" CodeFile="AnnualPaymentReport.aspx.cs" Inherits="AnnualPaymentReport" EnableEventValidation="false"%>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" Runat="Server">

        <div id="annualReport" class="jumbotron">
            <h3>Annual Report</h3>

        <%--<asp:GridView class="container" ID="GridView1" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" OnRowDataBound="GridView1_RowDataBound" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            <AlternatingRowStyle BackColor="#CCCCFF" BorderColor="Black" BorderStyle="None" />
            <Columns>
                <asp:BoundField DataField="InvoiceID" HeaderText="Invoice #" SortExpression="InvoiceID" />
                <asp:BoundField DataField="OrganizationName" HeaderText="Organization" SortExpression="OrganizationName" />
                <asp:BoundField DataField="Type" HeaderText="Payment Type" SortExpression="Type" />
                <asp:BoundField DataField="TotalCost" HeaderText="Amount Due" SortExpression="TotalCost" />
                <asp:BoundField DataField="DateCompleted" HeaderText="Date Completed" SortExpression="DateCompleted" />
                <asp:BoundField DataField="LastUpdated" HeaderText="Last Updated" SortExpression="LastUpdated" />
                <asp:BoundField DataField="LastUpdatedBy" HeaderText="Last Updated By" SortExpression="LastUpdatedBy" />
            </Columns>
        </asp:GridView>--%>
    </div>
    <%--<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:WildlifeCenterConnectionString3 %>" 
        SelectCommand="SELECT p.[InvoiceID], o.[OrganizationName], p.[Type], p.[TotalCost], p.[DateCompleted], p.[LastUpdated], p.[LastUpdatedBy] FROM [Payment] p inner join [Organization] o on p.OrganizationID = o.OrganizationID ORDER BY [InvoiceID], [DateCompleted]">

    </asp:SqlDataSource>--%>
</asp:Content>

