<%@ Page Title="" Language="C#" MasterPageFile="~/Main.master" AutoEventWireup="true" CodeFile="MonthlyPaymentReport.aspx.cs" Inherits="MonthlyPaymentReport" EnableEventValidation="false"%>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" Runat="Server">
    <%--<div id="monthlyReports" class="jumbotron">
        <h3>Monthly Report</h3>
        <div id="monthButtons" style="padding-bottom: 15px;">
                <asp:Button class="btn btn-primary" data-toggle="collapse" data-target="#jan" ID="btnJan" runat="server" Text="January" OnClientClick="return false"/>
                <asp:Button class="btn btn-primary" data-toggle="collapse" data-target="#feb" ID="btnFeb" runat="server" Text="February" OnClientClick="return false"/>
                <asp:Button class="btn btn-primary" data-toggle="collapse" data-target="#mar" ID="btnMar" runat="server" Text="March" OnClientClick="return false"/>
                <asp:Button class="btn btn-primary" data-toggle="collapse" data-target="#apr" ID="btnApr" runat="server" Text="April" OnClientClick="return false"/>
                <asp:Button class="btn btn-primary" data-toggle="collapse" data-target="#may" ID="btnMay" runat="server" Text="May" OnClientClick="return false"/>
                <asp:Button class="btn btn-primary" data-toggle="collapse" data-target="#jun" ID="btnJun" runat="server" Text="June" OnClientClick="return false"/>
                <asp:Button class="btn btn-primary" data-toggle="collapse" data-target="#jul" ID="btnJul" runat="server" Text="July" OnClientClick="return false"/>
                <asp:Button class="btn btn-primary" data-toggle="collapse" data-target="#aug" ID="btnAug" runat="server" Text="August" OnClientClick="return false"/>
                <asp:Button class="btn btn-primary" data-toggle="collapse" data-target="#sep" ID="btnSep" runat="server" Text="September" OnClientClick="return false"/>
                <asp:Button class="btn btn-primary" data-toggle="collapse" data-target="#oct" ID="btnOct" runat="server" Text="October" OnClientClick="return false"/>      
                <asp:Button class="btn btn-primary" data-toggle="collapse" data-target="#nov" ID="btnNov" runat="server" Text="November" OnClientClick="return false"/>
                <asp:Button class="btn btn-primary" data-toggle="collapse" data-target="#dec" ID="btnDec" runat="server" Text="December" OnClientClick="return false"/>
                
       </div>
       <div id="monthGrids">
           <div id="jan" class="collapse">
                <p>January</p>
               <asp:GridView ID="janGrid" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource2" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" ForeColor="#333333" GridLines="None">
            <AlternatingRowStyle BackColor="White" BorderColor="Black" BorderStyle="None" />
                   <Columns>
                        <asp:BoundField DataField="InvoiceID" HeaderText="Invoice #" SortExpression="InvoiceID" />
                        <asp:BoundField DataField="OrganizationName" HeaderText="Organization" SortExpression="OrganizationName" />
                        <asp:BoundField DataField="Type" HeaderText="Payment Type" SortExpression="Type" />
                        <asp:BoundField DataField="TotalCost" HeaderText="Amount Due" SortExpression="TotalCost" />
                        <asp:BoundField DataField="DateCompleted" HeaderText="Date Completed" SortExpression="DateCompleted" />
                        <asp:BoundField DataField="LastUpdated" HeaderText="Last Updated" SortExpression="LastUpdated" />
                        <asp:BoundField DataField="LastUpdatedBy" HeaderText="Last Updated By" SortExpression="LastUpdatedBy" />
                   </Columns>
                </asp:GridView>

                <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:WildlifeCenterConnectionString3 %>" SelectCommand="SELECT p.[InvoiceID], o.[OrganizationName], p.[Type], p.[TotalCost], p.[DateCompleted], p.[LastUpdated], p.[LastUpdatedBy] FROM [Payment] p inner join [Organization] o on p.OrganizationID = o.OrganizationID WHERE MONTH(p.[DateCompleted]) = '1' ORDER BY [InvoiceID], [DateCompleted]"></asp:SqlDataSource>
          </div>
           <div id="feb" class="collapse">
                <p>February</p>
               <asp:GridView ID="febGrid" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource3" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" ForeColor="#333333" GridLines="None">
            <AlternatingRowStyle BackColor="White" BorderColor="Black" BorderStyle="None" />
                   <Columns>
                        <asp:BoundField DataField="InvoiceID" HeaderText="Invoice #" SortExpression="InvoiceID" />
                        <asp:BoundField DataField="OrganizationName" HeaderText="Organization" SortExpression="OrganizationName" />
                        <asp:BoundField DataField="Type" HeaderText="Payment Type" SortExpression="Type" />
                        <asp:BoundField DataField="TotalCost" HeaderText="Amount Due" SortExpression="TotalCost" />
                        <asp:BoundField DataField="DateCompleted" HeaderText="Date Completed" SortExpression="DateCompleted" />
                        <asp:BoundField DataField="LastUpdated" HeaderText="Last Updated" SortExpression="LastUpdated" />
                        <asp:BoundField DataField="LastUpdatedBy" HeaderText="Last Updated By" SortExpression="LastUpdatedBy" />
                   </Columns>
                </asp:GridView>

                <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:WildlifeCenterConnectionString3 %>" SelectCommand="SELECT p.[InvoiceID], o.[OrganizationName], p.[Type], p.[TotalCost], p.[DateCompleted], p.[LastUpdated], p.[LastUpdatedBy] FROM [Payment] p inner join [Organization] o on p.OrganizationID = o.OrganizationID WHERE MONTH(p.[DateCompleted]) = '2' ORDER BY [InvoiceID], [DateCompleted]"></asp:SqlDataSource>

          </div>
           <div id="mar" class="collapse">
                <p>March</p>
               <asp:GridView ID="marGrid" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource4" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            <AlternatingRowStyle BackColor="#CCCCFF" BorderColor="Black" BorderStyle="None" />
                   <Columns>
                        <asp:BoundField DataField="InvoiceID" HeaderText="Invoice #" SortExpression="InvoiceID" />
                        <asp:BoundField DataField="OrganizationName" HeaderText="Organization" SortExpression="OrganizationName" />
                        <asp:BoundField DataField="Type" HeaderText="Payment Type" SortExpression="Type" />
                        <asp:BoundField DataField="TotalCost" HeaderText="Amount Due" SortExpression="TotalCost" />
                        <asp:BoundField DataField="DateCompleted" HeaderText="Date Completed" SortExpression="DateCompleted" />
                        <asp:BoundField DataField="LastUpdated" HeaderText="Last Updated" SortExpression="LastUpdated" />
                        <asp:BoundField DataField="LastUpdatedBy" HeaderText="Last Updated By" SortExpression="LastUpdatedBy" />
                   </Columns>
                </asp:GridView>

                <asp:SqlDataSource ID="SqlDataSource4" runat="server" ConnectionString="<%$ ConnectionStrings:WildlifeCenterConnectionString3 %>" SelectCommand="SELECT p.[InvoiceID], o.[OrganizationName], p.[Type], p.[TotalCost], p.[DateCompleted], p.[LastUpdated], p.[LastUpdatedBy] FROM [Payment] p inner join [Organization] o on p.OrganizationID = o.OrganizationID WHERE MONTH(p.[DateCompleted]) = '3' ORDER BY [InvoiceID], [DateCompleted]"></asp:SqlDataSource>

          </div>
           <div id="apr" class="collapse">
                <p>April</p>
               <asp:GridView ID="aprGrid" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource5" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            <AlternatingRowStyle BackColor="#CCCCFF" BorderColor="Black" BorderStyle="None" />
                   <Columns>
                        <asp:BoundField DataField="InvoiceID" HeaderText="Invoice #" SortExpression="InvoiceID" />
                        <asp:BoundField DataField="OrganizationName" HeaderText="Organization" SortExpression="OrganizationName" />
                        <asp:BoundField DataField="Type" HeaderText="Payment Type" SortExpression="Type" />
                        <asp:BoundField DataField="TotalCost" HeaderText="Amount Due" SortExpression="TotalCost" />
                        <asp:BoundField DataField="DateCompleted" HeaderText="Date Completed" SortExpression="DateCompleted" />
                        <asp:BoundField DataField="LastUpdated" HeaderText="Last Updated" SortExpression="LastUpdated" />
                        <asp:BoundField DataField="LastUpdatedBy" HeaderText="Last Updated By" SortExpression="LastUpdatedBy" />
                   </Columns>
                </asp:GridView>

                <asp:SqlDataSource ID="SqlDataSource5" runat="server" ConnectionString="<%$ ConnectionStrings:WildlifeCenterConnectionString3 %>" SelectCommand="SELECT p.[InvoiceID], o.[OrganizationName], p.[Type], p.[TotalCost], p.[DateCompleted], p.[LastUpdated], p.[LastUpdatedBy] FROM [Payment] p inner join [Organization] o on p.OrganizationID = o.OrganizationID WHERE MONTH(p.[DateCompleted]) = '4' ORDER BY [InvoiceID], [DateCompleted]"></asp:SqlDataSource>

          </div>
           <div id="may" class="collapse">
                <p>May</p>
               <asp:GridView ID="mayGrid" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource6" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            <AlternatingRowStyle BackColor="#CCCCFF" BorderColor="Black" BorderStyle="None" />
                   <Columns>
                        <asp:BoundField DataField="InvoiceID" HeaderText="Invoice #" SortExpression="InvoiceID" />
                        <asp:BoundField DataField="OrganizationName" HeaderText="Organization" SortExpression="OrganizationName" />
                        <asp:BoundField DataField="Type" HeaderText="Payment Type" SortExpression="Type" />
                        <asp:BoundField DataField="TotalCost" HeaderText="Amount Due" SortExpression="TotalCost" />
                        <asp:BoundField DataField="DateCompleted" HeaderText="Date Completed" SortExpression="DateCompleted" />
                        <asp:BoundField DataField="LastUpdated" HeaderText="Last Updated" SortExpression="LastUpdated" />
                        <asp:BoundField DataField="LastUpdatedBy" HeaderText="Last Updated By" SortExpression="LastUpdatedBy" />
                   </Columns>
                </asp:GridView>

                <asp:SqlDataSource ID="SqlDataSource6" runat="server" ConnectionString="<%$ ConnectionStrings:WildlifeCenterConnectionString3 %>" SelectCommand="SELECT p.[InvoiceID], o.[OrganizationName], p.[Type], p.[TotalCost], p.[DateCompleted], p.[LastUpdated], p.[LastUpdatedBy] FROM [Payment] p inner join [Organization] o on p.OrganizationID = o.OrganizationID WHERE MONTH(p.[DateCompleted]) = '5' ORDER BY [InvoiceID], [DateCompleted]"></asp:SqlDataSource>

          </div>
           <div id="jun" class="collapse">
                <p>June</p>
               <asp:GridView ID="junGrid" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource7" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            <AlternatingRowStyle BackColor="#CCCCFF" BorderColor="Black" BorderStyle="None" />
                   <Columns>
                        <asp:BoundField DataField="InvoiceID" HeaderText="Invoice #" SortExpression="InvoiceID" />
                        <asp:BoundField DataField="OrganizationName" HeaderText="Organization" SortExpression="OrganizationName" />
                        <asp:BoundField DataField="Type" HeaderText="Payment Type" SortExpression="Type" />
                        <asp:BoundField DataField="TotalCost" HeaderText="Amount Due" SortExpression="TotalCost" />
                        <asp:BoundField DataField="DateCompleted" HeaderText="Date Completed" SortExpression="DateCompleted" />
                        <asp:BoundField DataField="LastUpdated" HeaderText="Last Updated" SortExpression="LastUpdated" />
                        <asp:BoundField DataField="LastUpdatedBy" HeaderText="Last Updated By" SortExpression="LastUpdatedBy" />
                   </Columns>
                </asp:GridView>

                <asp:SqlDataSource ID="SqlDataSource7" runat="server" ConnectionString="<%$ ConnectionStrings:WildlifeCenterConnectionString3 %>" SelectCommand="SELECT p.[InvoiceID], o.[OrganizationName], p.[Type], p.[TotalCost], p.[DateCompleted], p.[LastUpdated], p.[LastUpdatedBy] FROM [Payment] p inner join [Organization] o on p.OrganizationID = o.OrganizationID WHERE MONTH(p.[DateCompleted]) = '6' ORDER BY [InvoiceID], [DateCompleted]"></asp:SqlDataSource>

          </div>
           <div id="jul" class="collapse">
                <p>July</p>
               <asp:GridView ID="julGrid" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource8" OnRowDataBound="julGrid_RowDataBound" OnSelectedIndexChanged="julGrid_SelectedIndexChanged" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                   <AlternatingRowStyle BackColor="#CCCCFF" BorderColor="Black" BorderStyle="None" />
                   <Columns>
                        <asp:BoundField DataField="InvoiceID" HeaderText="Invoice #" SortExpression="InvoiceID" />
                        <asp:BoundField DataField="OrganizationName" HeaderText="Organization" SortExpression="OrganizationName" />
                        <asp:BoundField DataField="Type" HeaderText="Payment Type" SortExpression="Type" />
                        <asp:BoundField DataField="TotalCost" HeaderText="Amount Due" SortExpression="TotalCost" />
                        <asp:BoundField DataField="DateCompleted" HeaderText="Date Completed" SortExpression="DateCompleted" />
                        <asp:BoundField DataField="LastUpdated" HeaderText="Last Updated" SortExpression="LastUpdated" />
                        <asp:BoundField DataField="LastUpdatedBy" HeaderText="Last Updated By" SortExpression="LastUpdatedBy" />
                   </Columns>
                </asp:GridView>

                <asp:SqlDataSource ID="SqlDataSource8" runat="server" ConnectionString="<%$ ConnectionStrings:WildlifeCenterConnectionString3 %>" SelectCommand="SELECT p.[InvoiceID], o.[OrganizationName], p.[Type], p.[TotalCost], p.[DateCompleted], p.[LastUpdated], p.[LastUpdatedBy] FROM [Payment] p inner join [Organization] o on p.OrganizationID = o.OrganizationID WHERE MONTH(p.[DateCompleted]) = '7' ORDER BY [InvoiceID], [DateCompleted]"></asp:SqlDataSource>

          </div>
           <div id="aug" class="collapse">
                <p>August</p>
               <asp:GridView ID="augGrid" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource9" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            <AlternatingRowStyle BackColor="#CCCCFF" BorderColor="Black" BorderStyle="None" />
                   <Columns>
                        <asp:BoundField DataField="InvoiceID" HeaderText="Invoice #" SortExpression="InvoiceID" />
                        <asp:BoundField DataField="OrganizationName" HeaderText="Organization" SortExpression="OrganizationName" />
                        <asp:BoundField DataField="Type" HeaderText="Payment Type" SortExpression="Type" />
                        <asp:BoundField DataField="TotalCost" HeaderText="Amount Due" SortExpression="TotalCost" />
                        <asp:BoundField DataField="DateCompleted" HeaderText="Date Completed" SortExpression="DateCompleted" />
                        <asp:BoundField DataField="LastUpdated" HeaderText="Last Updated" SortExpression="LastUpdated" />
                        <asp:BoundField DataField="LastUpdatedBy" HeaderText="Last Updated By" SortExpression="LastUpdatedBy" />
                   </Columns>
                </asp:GridView>

                <asp:SqlDataSource ID="SqlDataSource9" runat="server" ConnectionString="<%$ ConnectionStrings:WildlifeCenterConnectionString3 %>" SelectCommand="SELECT p.[InvoiceID], o.[OrganizationName], p.[Type], p.[TotalCost], p.[DateCompleted], p.[LastUpdated], p.[LastUpdatedBy] FROM [Payment] p inner join [Organization] o on p.OrganizationID = o.OrganizationID WHERE MONTH(p.[DateCompleted]) = '8' ORDER BY [InvoiceID], [DateCompleted]"></asp:SqlDataSource>

          </div>
           <div id="sep" class="collapse">
                <p>September</p>
               <asp:GridView ID="sepGrid" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource10" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            <AlternatingRowStyle BackColor="#CCCCFF" BorderColor="Black" BorderStyle="None" />
                   <Columns>
                        <asp:BoundField DataField="InvoiceID" HeaderText="Invoice #" SortExpression="InvoiceID" />
                        <asp:BoundField DataField="OrganizationName" HeaderText="Organization" SortExpression="OrganizationName" />
                        <asp:BoundField DataField="Type" HeaderText="Payment Type" SortExpression="Type" />
                        <asp:BoundField DataField="TotalCost" HeaderText="Amount Due" SortExpression="TotalCost" />
                        <asp:BoundField DataField="DateCompleted" HeaderText="Date Completed" SortExpression="DateCompleted" />
                        <asp:BoundField DataField="LastUpdated" HeaderText="Last Updated" SortExpression="LastUpdated" />
                        <asp:BoundField DataField="LastUpdatedBy" HeaderText="Last Updated By" SortExpression="LastUpdatedBy" />
                   </Columns>
                </asp:GridView>

                <asp:SqlDataSource ID="SqlDataSource10" runat="server" ConnectionString="<%$ ConnectionStrings:WildlifeCenterConnectionString3 %>" SelectCommand="SELECT p.[InvoiceID], o.[OrganizationName], p.[Type], p.[TotalCost], p.[DateCompleted], p.[LastUpdated], p.[LastUpdatedBy] FROM [Payment] p inner join [Organization] o on p.OrganizationID = o.OrganizationID WHERE MONTH(p.[DateCompleted]) = '9' ORDER BY [InvoiceID], [DateCompleted]"></asp:SqlDataSource>

          </div>
           <div id="oct" class="collapse">
                <p>October</p>
               <asp:GridView ID="octGrid" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource11" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            <AlternatingRowStyle BackColor="#CCCCFF" BorderColor="Black" BorderStyle="None" />
                   <Columns>
                        <asp:BoundField DataField="InvoiceID" HeaderText="Invoice #" SortExpression="InvoiceID" />
                        <asp:BoundField DataField="OrganizationName" HeaderText="Organization" SortExpression="OrganizationName" />
                        <asp:BoundField DataField="Type" HeaderText="Payment Type" SortExpression="Type" />
                        <asp:BoundField DataField="TotalCost" HeaderText="Amount Due" SortExpression="TotalCost" />
                        <asp:BoundField DataField="DateCompleted" HeaderText="Date Completed" SortExpression="DateCompleted" />
                        <asp:BoundField DataField="LastUpdated" HeaderText="Last Updated" SortExpression="LastUpdated" />
                        <asp:BoundField DataField="LastUpdatedBy" HeaderText="Last Updated By" SortExpression="LastUpdatedBy" />
                   </Columns>
                </asp:GridView>

                <asp:SqlDataSource ID="SqlDataSource11" runat="server" ConnectionString="<%$ ConnectionStrings:WildlifeCenterConnectionString3 %>" SelectCommand="SELECT p.[InvoiceID], o.[OrganizationName], p.[Type], p.[TotalCost], p.[DateCompleted], p.[LastUpdated], p.[LastUpdatedBy] FROM [Payment] p inner join [Organization] o on p.OrganizationID = o.OrganizationID WHERE MONTH(p.[DateCompleted]) = '10' ORDER BY [InvoiceID], [DateCompleted]"></asp:SqlDataSource>

          </div>
           <div id="nov" class="collapse">
                <p>November</p>
               <asp:GridView ID="novGrid" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource12" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            <AlternatingRowStyle BackColor="#CCCCFF" BorderColor="Black" BorderStyle="None" />
                   <Columns>
                        <asp:BoundField DataField="InvoiceID" HeaderText="Invoice #" SortExpression="InvoiceID" />
                        <asp:BoundField DataField="OrganizationName" HeaderText="Organization" SortExpression="OrganizationName" />
                        <asp:BoundField DataField="Type" HeaderText="Payment Type" SortExpression="Type" />
                        <asp:BoundField DataField="TotalCost" HeaderText="Amount Due" SortExpression="TotalCost" />
                        <asp:BoundField DataField="DateCompleted" HeaderText="Date Completed" SortExpression="DateCompleted" />
                        <asp:BoundField DataField="LastUpdated" HeaderText="Last Updated" SortExpression="LastUpdated" />
                        <asp:BoundField DataField="LastUpdatedBy" HeaderText="Last Updated By" SortExpression="LastUpdatedBy" />
                   </Columns>
                </asp:GridView>

                <asp:SqlDataSource ID="SqlDataSource12" runat="server" ConnectionString="<%$ ConnectionStrings:WildlifeCenterConnectionString3 %>" SelectCommand="SELECT p.[InvoiceID], o.[OrganizationName], p.[Type], p.[TotalCost], p.[DateCompleted], p.[LastUpdated], p.[LastUpdatedBy] FROM [Payment] p inner join [Organization] o on p.OrganizationID = o.OrganizationID WHERE MONTH(p.[DateCompleted]) = '11' ORDER BY [InvoiceID], [DateCompleted]"></asp:SqlDataSource>

          </div>
           <div id="dec" class="collapse">
                <p>December</p>
               <asp:GridView ID="decGrid" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource13" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            <AlternatingRowStyle BackColor="#CCCCFF" BorderColor="Black" BorderStyle="None" />
                   <Columns>
                        <asp:BoundField DataField="InvoiceID" HeaderText="Invoice #" SortExpression="InvoiceID" />
                        <asp:BoundField DataField="OrganizationName" HeaderText="Organization" SortExpression="OrganizationName" />
                        <asp:BoundField DataField="Type" HeaderText="Payment Type" SortExpression="Type" />
                        <asp:BoundField DataField="TotalCost" HeaderText="Amount Due" SortExpression="TotalCost" />
                        <asp:BoundField DataField="DateCompleted" HeaderText="Date Completed" SortExpression="DateCompleted" />
                        <asp:BoundField DataField="LastUpdated" HeaderText="Last Updated" SortExpression="LastUpdated" />
                        <asp:BoundField DataField="LastUpdatedBy" HeaderText="Last Updated By" SortExpression="LastUpdatedBy" />
                   </Columns>
                </asp:GridView>

                <asp:SqlDataSource ID="SqlDataSource13" runat="server" ConnectionString="<%$ ConnectionStrings:WildlifeCenterConnectionString3 %>" SelectCommand="SELECT p.[InvoiceID], o.[OrganizationName], p.[Type], p.[TotalCost], p.[DateCompleted], p.[LastUpdated], p.[LastUpdatedBy] FROM [Payment] p inner join [Organization] o on p.OrganizationID = o.OrganizationID WHERE MONTH(p.[DateCompleted]) = '12' ORDER BY [InvoiceID], [DateCompleted]"></asp:SqlDataSource>

          </div>
       </div>

    </div>--%>
</asp:Content>

